name: flutter_smart_env
description: smart-env client for Flutter.
version: 0.0.1
author: Alexander Pokhodyun
homepage: https://github.com/karbunkul/smart-env

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
